Fix OpenVPN script for Debian 13 and Ubuntu 24

diff --git a/files/openvpn b/files/openvpn
--- a/files/openvpn
+++ b/files/openvpn
@@ -7,33 +7,111 @@
 # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 
 export DEBIAN_FRONTEND=noninteractive
-OS=`uname -m`;
-MYIP=$(wget -qO- ipinfo.io/ip);
-domain=$(cat /root/domain)
-#MYIP2="s/xxxxxxxxx/$MYIP/g";
-MYIP2="s/xxxxxxxxx/$domain/g";
 
+OS="$(uname -m)"
+
+# Public IP ONLY (no domain)
+MYIP="$(wget -qO- ipinfo.io/ip 2>/dev/null || curl -sS ipv4.icanhazip.com 2>/dev/null || echo "127.0.0.1")"
+
+# Host used inside OVPN and HTML (always IP)
+WEB_HOST="$MYIP"
+
+# Replace "xxxxxxxxx" in ovpn configs with server IP
+MYIP2="s/xxxxxxxxx/$WEB_HOST/g"
+
+# ---------------------------------------------------
+# Download and unpack server-side OpenVPN configs
+# ---------------------------------------------------
 function ovpn_install() {
     rm -rf /etc/openvpn
     mkdir -p /etc/openvpn
-    wget -O /etc/openvpn/vpn.zip "https://raw.githubusercontent.com/jaka1m/project/main/ssh/vpn.zip" >/dev/null 2>&1 
-    unzip -d /etc/openvpn/ /etc/openvpn/vpn.zip
+
+    wget -q -O /etc/openvpn/vpn.zip \
+        "https://raw.githubusercontent.com/jaka1m/project/main/ssh/vpn.zip" >/dev/null 2>&1
+
+    unzip -d /etc/openvpn/ /etc/openvpn/vpn.zip >/dev/null 2>&1
     rm -f /etc/openvpn/vpn.zip
-    chown -R root:root /etc/openvpn/server/easy-rsa/
-}
-function config_easy() {
-    cd
-    mkdir -p /usr/lib/openvpn/
-    cp /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so /usr/lib/openvpn/openvpn-plugin-auth-pam.so
-    sed -i 's/#AUTOSTART="all"/AUTOSTART="all"/g' /etc/default/openvpn
-    systemctl enable --now openvpn-server@server-tcp
-    systemctl enable --now openvpn-server@server-udp
-    /etc/init.d/openvpn restart
+
+    chown -R root:root /etc/openvpn/server/easy-rsa/ 2>/dev/null || true
 }
 
+# ---------------------------------------------------
+# Configure OpenVPN service & PAM plugin safely
+# ---------------------------------------------------
+function config_easy() {
+    mkdir -p /usr/lib/openvpn/
+
+    # Try to find the auth PAM plugin in common locations
+    local PLUGIN_SRC=""
+    for p in \
+        /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so \
+        /usr/lib/openvpn/plugins/openvpn-plugin-auth-pam.so \
+        /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so
+    do
+        if [[ -f "$p" ]]; then
+            PLUGIN_SRC="$p"
+            break
+        fi
+    done
+
+    # Copy plugin if found (do not fail if not found)
+    if [[ -n "$PLUGIN_SRC" ]]; then
+        cp "$PLUGIN_SRC" /usr/lib/openvpn/openvpn-plugin-auth-pam.so 2>/dev/null || true
+    fi
+
+    # Ensure /etc/default/openvpn exists and AUTOSTART is set to "all"
+    if [[ ! -f /etc/default/openvpn ]]; then
+        echo 'AUTOSTART="all"' > /etc/default/openvpn
+    else
+        if grep -q '^#\?AUTOSTART=' /etc/default/openvpn 2>/dev/null; then
+            sed -i 's/^#\?AUTOSTART=.*/AUTOSTART="all"/' /etc/default/openvpn
+        else
+            echo 'AUTOSTART="all"' >> /etc/default/openvpn
+        fi
+    fi
+
+    # Try to enable all common OpenVPN systemd units (ignore errors)
+    for svc in \
+        openvpn-server@server-tcp.service \
+        openvpn-server@server-udp.service \
+        openvpn@server-tcp.service \
+        openvpn@server-udp.service \
+        openvpn.service
+    do
+        systemctl enable --now "$svc" 2>/dev/null || true
+    done
+
+    # Restart OpenVPN using whichever method is available
+    if [[ -x /etc/init.d/openvpn ]]; then
+        /etc/init.d/openvpn restart 2>/dev/null || true
+    else
+        systemctl restart openvpn-server@server-tcp.service 2>/dev/null || true
+        systemctl restart openvpn-server@server-udp.service 2>/dev/null || true
+        systemctl restart openvpn.service 2>/dev/null || true
+    fi
+}
+
+# ---------------------------------------------------
+# Create client configs (TCP / UDP / WS-SSL / SSL)
+# ---------------------------------------------------
 function make_follow() {
+    # Enable IPv4 forwarding at runtime
     echo 1 > /proc/sys/net/ipv4/ip_forward
-    sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
+
+    # Ensure /etc/sysctl.conf exists and enable net.ipv4.ip_forward=1
+    if [[ ! -f /etc/sysctl.conf ]]; then
+        touch /etc/sysctl.conf
+    fi
+    if grep -q '^#\?net.ipv4.ip_forward' /etc/sysctl.conf 2>/dev/null; then
+        sed -i 's/^#\?net.ipv4.ip_forward=.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
+    else
+        echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
+    fi
+
+    # (Optional) apply sysctl changes – ignore errors on some systems
+    sysctl -p 2>/dev/null || true
+
+    # ----------------- TCP OVPN -----------------
 cat > /etc/openvpn/tcp.ovpn <<-END
 client
 dev tun
@@ -48,8 +126,9 @@ auth-user-pass
 comp-lzo
 verb 3
 END
-    
-    sed -i $MYIP2 /etc/openvpn/tcp.ovpn;
+    sed -i "$MYIP2" /etc/openvpn/tcp.ovpn
+
+    # ----------------- UDP OVPN -----------------
 cat > /etc/openvpn/udp.ovpn <<-END
 client
 dev tun
@@ -64,8 +143,9 @@ auth-user-pass
 comp-lzo
 verb 3
 END
-    
-    sed -i $MYIP2 /etc/openvpn/udp.ovpn;
+    sed -i "$MYIP2" /etc/openvpn/udp.ovpn
+
+    # -------------- WS-SSL OVPN -----------------
 cat > /etc/openvpn/ws-ssl.ovpn <<-END
 client
 dev tun
@@ -80,7 +160,9 @@ auth-user-pass
 comp-lzo
 verb 3
 END
-    sed -i $MYIP2 /etc/openvpn/ws-ssl.ovpn;
+    sed -i "$MYIP2" /etc/openvpn/ws-ssl.ovpn
+
+    # ---------------- SSL OVPN ------------------
 cat > /etc/openvpn/ssl.ovpn <<-END
 client
 dev tun
@@ -95,63 +177,130 @@ auth-user-pass
 comp-lzo
 verb 3
 END
-    sed -i $MYIP2 /etc/openvpn/ssl.ovpn;
+    sed -i "$MYIP2" /etc/openvpn/ssl.ovpn
 }
+
+# ---------------------------------------------------
+# Attach CA cert and prepare download site
+# ---------------------------------------------------
 function cert_ovpn() {
+    # Attach CA to each config and copy to web directory
     echo '<ca>' >> /etc/openvpn/tcp.ovpn
     cat /etc/openvpn/server/ca.crt >> /etc/openvpn/tcp.ovpn
     echo '</ca>' >> /etc/openvpn/tcp.ovpn
     cp /etc/openvpn/tcp.ovpn /var/www/html/tcp.ovpn
+
     echo '<ca>' >> /etc/openvpn/udp.ovpn
     cat /etc/openvpn/server/ca.crt >> /etc/openvpn/udp.ovpn
     echo '</ca>' >> /etc/openvpn/udp.ovpn
     cp /etc/openvpn/udp.ovpn /var/www/html/udp.ovpn
+
     echo '<ca>' >> /etc/openvpn/ws-ssl.ovpn
     cat /etc/openvpn/server/ca.crt >> /etc/openvpn/ws-ssl.ovpn
     echo '</ca>' >> /etc/openvpn/ws-ssl.ovpn
     cp /etc/openvpn/ws-ssl.ovpn /var/www/html/ws-ssl.ovpn
+
+    echo '<ca>' >> /etc/openvpn/ssl.ovpn
+    cat /etc/openvpn/server/ca.crt >> /etc/openvpn/ssl.ovpn
     echo '</ca>' >> /etc/openvpn/ssl.ovpn
-    cp /etc/openvpn/ws-ssl.ovpn /var/www/html/ssl.ovpn
-    
-# Delete script
- 
-cd /var/www/html/
-zip Kyt-Project.zip tcp.ovpn udp.ovpn ssl.ovpn ws-ssl.ovpn > /dev/null 2>&1
-cd
+    cp /etc/openvpn/ssl.ovpn /var/www/html/ssl.ovpn
+
+    # Create zip archive of all configs
+    cd /var/www/html/ || exit 0
+    zip Kyt-Project.zip tcp.ovpn udp.ovpn ssl.ovpn ws-ssl.ovpn >/dev/null 2>&1
+    cd
+
+    # Simple HTML download page (will be patched with IP)
 cat <<'mySiteOvpn' > /var/www/html/index.html
 <!DOCTYPE html>
 <html lang="en">
-
 <!-- Simple OVPN Download site -->
-
-<head><meta charset="utf-8" /><title>OVPN Config Download</title><meta name="description" content="Server" /><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" /><meta name="theme-color" content="#000000" /><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"><link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet"></head><body><div class="container justify-content-center" style="margin-top:9em;margin-bottom:5em;"><div class="col-md"><div class="view"><img src="https://openvpn.net/wp-content/uploads/openvpn.jpg" class="card-img-top"><div class="mask rgba-white-slight"></div></div><div class="card"><div class="card-body"><h5 class="card-title">Config List</h5><br /><ul class="list-group">
-
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>TCP <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/tcp.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>UDP <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/udp.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>SSL <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/ssl.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p> WS SSL <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/ws-ssl.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p> ALL.zip <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/Kyt-Project.zip" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-
-</ul></div></div></div></div></body></html>
+<head>
+  <meta charset="utf-8" />
+  <title>OVPN Config Download</title>
+  <meta name="description" content="Server" />
+  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
+  <meta name="theme-color" content="#000000" />
+  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
+  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
+  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">
+</head>
+<body>
+<div class="container justify-content-center" style="margin-top:9em;margin-bottom:5em;">
+  <div class="col-md">
+    <div class="view">
+      <img src="https://openvpn.net/wp-content/uploads/openvpn.jpg" class="card-img-top">
+      <div class="mask rgba-white-slight"></div>
+    </div>
+    <div class="card">
+      <div class="card-body">
+        <h5 class="card-title">Config List</h5><br />
+        <ul class="list-group">
+          <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+            <p>TCP <span class="badge light-blue darken-4">Android / iOS / PC / Modem</span></p>
+            <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/tcp.ovpn" style="float:right;">
+              <i class="fa fa-download"></i> Download
+            </a>
+          </li>
+          <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+            <p>UDP <span class="badge light-blue darken-4">Android / iOS / PC / Modem</span></p>
+            <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/udp.ovpn" style="float:right;">
+              <i class="fa fa-download"></i> Download
+            </a>
+          </li>
+          <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+            <p>SSL <span class="badge light-blue darken-4">Android / iOS / PC / Modem</span></p>
+            <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/ssl.ovpn" style="float:right;">
+              <i class="fa fa-download"></i> Download
+            </a>
+          </li>
+          <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+            <p>WS SSL <span class="badge light-blue darken-4">Android / iOS / PC / Modem</span></p>
+            <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/ws-ssl.ovpn" style="float:right;">
+              <i class="fa fa-download"></i> Download
+            </a>
+          </li>
+          <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+            <p>ALL.zip <span class="badge light-blue darken-4">Android / iOS / PC / Modem</span></p>
+            <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/Kyt-Project.zip" style="float:right;">
+              <i class="fa fa-download"></i> Download
+            </a>
+          </li>
+        </ul>
+      </div>
+    </div>
+  </div>
+</div>
+</body>
+</html>
 mySiteOvpn
 
-sed -i "s|IP-ADDRESSS|$(curl -sS ifconfig.me)|g" /var/www/html/index.html
-
+    # Replace placeholder with SERVER IP only
+    sed -i "s|IP-ADDRESSS|$WEB_HOST|g" /var/www/html/index.html
 }
 
+# ---------------------------------------------------
+# Main install wrapper
+# ---------------------------------------------------
 function install_ovpn() {
     ovpn_install
     config_easy
     make_follow
-    make_follow
+    make_follow          # kept as in original script
     cert_ovpn
-    systemctl enable openvpn
-    systemctl start openvpn
-    /etc/init.d/openvpn restart
-    
+
+    # Enable and start generic openvpn service if it exists
+    systemctl enable openvpn 2>/dev/null || true
+    systemctl start openvpn 2>/dev/null || true
+
+    # Final restart using any available method
+    if [[ -x /etc/init.d/openvpn ]]; then
+        /etc/init.d/openvpn restart 2>/dev/null || true
+    else
+        systemctl restart openvpn-server@server-tcp.service 2>/dev/null || true
+        systemctl restart openvpn-server@server-udp.service 2>/dev/null || true
+        systemctl restart openvpn.service 2>/dev/null || true
+    fi
 }
+
 install_ovpn
